swagger: '2.0'
info:
  description: >-
    Live data , historic records and technical indicators for the crypto
    industry.
  version: 1.0.0
  title: Metacortex API
  contact:
    name: Tihomir Stoychev Stoychev
    url: 'http://github.com/tihomir22/'
    email: tihomir_alcudia3@hotmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8956'
basePath: /
tags:
  - name: price-controller
    description: Price Controller
paths:
  /historic:
    get:
      tags:
        - price-controller
      summary: Historic data
      description: Get the historic data for a cryptocurrency
      operationId: getHistoricUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HistoricDataWrapper'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /price:
    get:
      tags:
        - price-controller
      summary: Live Price
      description: Returns the live price data about a cryptocurrency asset
      operationId: getPriceUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnlyPrice'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/dema:
    get:
      tags:
        - price-controller
      summary: Double Exponential MA
      description: Get the double exponential moving average
      operationId: recuperarDEMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/ema:
    get:
      tags:
        - price-controller
      summary: Exponential MA
      description: Get the exponential moving average
      operationId: recuperarEMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/kama:
    get:
      tags:
        - price-controller
      summary: Kaufman Adaptive MA
      description: Get the kaufman's adaptive moving average
      operationId: recuperarKAMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/mama:
    get:
      tags:
        - price-controller
      summary: MESA Adaptive MA
      description: Get the MESA adaptive moving average
      operationId: recuperarMAMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/rsi:
    get:
      tags:
        - price-controller
      summary: Relative Strength Index
      description: Get the relative strength index
      operationId: recuperarRSIUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/sma:
    get:
      tags:
        - price-controller
      summary: Simple Moving Average
      description: Get the simple moving average
      operationId: recuperarSMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/t3:
    get:
      tags:
        - price-controller
      summary: T3 MA
      description: Get the t3's moving average
      operationId: recuperarT3UsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/tema:
    get:
      tags:
        - price-controller
      summary: Triple Exponential MA
      description: Get the triple's exponential moving average
      operationId: recuperarTEMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/tma:
    get:
      tags:
        - price-controller
      summary: Triangular MA
      description: Get the tringular's moving average
      operationId: recuperarTMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Tecnichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /technical/wma:
    get:
      tags:
        - price-controller
      summary: Weighted MA
      description: Get the weighted's moving average
      operationId: recuperarWMAUsingGET
      produces:
        - application/json
      parameters:
        - name: base
          in: query
          description: Base asset
          required: true
          type: string
        - name: counter
          in: query
          description: Counter asset
          required: true
          type: string
        - name: historicInterval
          in: query
          description: 'Historic Interval [1m,3m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M]'
          required: true
          type: string
        - name: indicatorInterval
          in: query
          description: 'Technichal''s Indicator Interval [10,20,50,100,200,500,...]'
          required: true
          type: string
        - name: seriesType
          in: query
          description: 'Price''s series type [open,close,high,low]'
          required: true
          type: string
        - name: tipoSeriesIndicador
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnicalRegistry'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  HistoricData:
    type: object
    properties:
      close:
        type: number
        format: double
        example: 10665.1
        description: Close historical price
      high:
        type: number
        format: double
        example: 11770.2
        description: High historical price
      low:
        type: number
        format: double
        example: 9575.1
        description: Low historical price
      open:
        type: number
        format: double
        example: 10500.2
        description: Open historical price
      open_time:
        type: string
        example: 1563700675
        description: Open time of this candle
      volume:
        type: number
        format: double
        example: 3410115.1
        description: Volume
    title: HistoricData
    description: Raw History data model
  HistoricDataWrapper:
    type: object
    properties:
      numRecords:
        type: integer
        format: int32
        example: 500
        description: Number of historic entries returned
      period:
        type: string
        example: 1h
        description: Period of the historic data
      rawHistoricData:
        type: array
        description: List of Historic Data objects
        items:
          $ref: '#/definitions/HistoricData'
    title: HistoricDataWrapper
    description: Wrapper for the historic data
  OnlyPrice:
    type: object
    properties:
      asset:
        type: string
        example: BTCUSDT
        description: Name of the asset
      price:
        type: number
        format: double
        example: '10531,34'
        description: Live price of the asset above
      timestamp:
        type: integer
        format: int64
        example: 1563566865
        description: Curremt timestamp of the request
    title: OnlyPrice
    description: Model for the response of live price data.
  TechnicalRegistry:
    type: object
    properties:
      date:
        type: string
        format: date-time
        example: 1563700393
        description: 'Date of the technical registry '
      historicPrice:
        type: number
        format: double
        example: 10343.34
        description: Historic price attached to the technical indicator registry below
      numRegistry:
        type: integer
        format: int32
        example: 1
        description: 'Number of the record , similar to id'
      technicalIndicator:
        type: number
        format: double
        example: 10255.14
        description: Technical indicator registry
    title: TechnicalRegistry
    description: Raw Technical Indicator Record